
# the tasks to be scheduled
Task[] tasks
# the earliest time for the first execution
time earliest_start
---

# the order the tasks should be executed in
uint64[] task_order

# the start time of each task
time[] execution_times

