strands_executive_msgs/MdpDomainSpec spec
---

---
float64 success_prob
float64 expected_time
float64 expected_prog
string starting_waypoint #only this is filled atm
string executed_action #only this is filled atm
uint8 execution_status #only this is filled atm. interpert using actionlib_msgs/GoalStatus
string ending_waypoint
string next_action