bool exit_forbidden_nodes #true->finds and executes fastest route out of forbidden nodes from current state. #false ->assuming robot is not in a forbidden node, finds and executes fastest route to node target_id from current state
string target_id
string time_of_day #for future use, for now should always be 'all_day'
---

---
float64 expected_time