strands_executive_msgs/MdpDomainSpec spec
---

---
float64 probability
float64 prog_reward
duration expected_time
string current_waypoint
string executed_action
uint8 execution_status # interpert using actionlib_msgs/GoalStatus
string next_action
string[] final_waypoints #to be filled
float64[] final_waypoints_probabilities #to be filled